#!/usr/bin/env node
const path = require('path')
const { exec } = require('childprocess-helper')
const { username, password } = require('./tmp-ssh-auth')

Object.assign(process.env, {
  SLRUN_REMOTE_API_SERVER_URL: 'http://127.0.0.1:4100/api',
  // BD: TODO use user login or auth key to ssh
  TEMP_SSH_USERNAME: username,
  TEMP_SSH_PASSWORD: password
})

exec(process.argv[0], [path.join(__dirname, 'packages/slrun'), ...process.argv.slice(2)])
